### ISSUE TITLE
پالایشگاه نبریز : کاربری که لیست اکتیو می گیرد باید ادمین باشد برای خوشزبان که ادمین نیست خطا می دهد

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/dashboard#102]
دکمه دریافت لیست دو اضاف شود
با کد زیر که در بی اس سی استفاده کردیم خطا نداد لطفا به داشبورد نیز اضافه شود
PrincipalContext(ContextType.Domain, "10.0.0.1", "DC=csroll,DC=local", ContextOptions.SimpleBind, "csroll\\Hash", "1234"))

**Comment by azetroma** [comment]
امکان اضافه کردن Container در زمان دریافت لیست اضافه شد
نسخه ۷.۶.۶
