### ISSUE TITLE
مشکل در ارائه دمو : اگر با کاربری وارد شویم و داشبورد را ببندیم دیگر اجاره ورود سیستم با همان کاربر را نمی دهد و محدودیت کاربر میدهد

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/dashboard#104]
روی لپتاپ من این مشکل در نسخه جدید بوجود آمده
روی بی اس سی روی یک شاخص که وارد داشبورد میشوم روی شاخص دوم خطا می دهد

**Comment by azetroma** [comment]
در حال حاضر اجازه ورود با یک نام کاربری داده می‌شود و هر سی ثانیه یک بار کاربرانی که مجوز ندارند از سیستم لاگ اوت می‌شوند.

در نسخه ۷.۶.۶ درست شد.
