### ISSUE TITLE
روي اعصاب كاربر : با عوض كردن نام شاخص در نمودار كليه تنظيمات رنگ و خطي بودن و غيره ريست ميشه و بايد دوباره انتخاب شوند

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/dashboard#55]

**Comment by azetroma** [comment]
در صورت تغییر نام ستون در قسمت فرمول نویسی، نام شاخص نیز تغییر می‌کند و امکانی نیست که مشخص شود شاخص‌های قبلی با جدید چه ارتباطی دارند.
در حال حاضر با روش موجود امکان حل این مشکل وجود ندارد
