### ISSUE TITLE
تكوين : تايع محاسبه روي بعد هاي مختلف متفاوت باشند

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/dashboard#57]
مثلا در بعد ماه كه هستيم تعداد افراد را نشان دهد
ولي در بعد سال كه ميرويم ميانگين بگيرد

**Comment by azetroma** [comment]
در حال حاضر با توجه به زیرساخت امکان اضافه کردن این ویژگی امکان پذیر نیست
