### ISSUE TITLE
سورت نمایش نام صفحات بهم ریخته لطفا بر اساس معکوس ورود اطلاعات صفحه باشد

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/dashboard#58]
در هنگام ثبت نمودار و انتخاب صفحه مورد نیاز کلی باید بگردیم در صورتی که قبلا آخرین صفحه صفحه جدید بود
لطفا صفحات جدید در ابتدا بیایند

**Comment by azetroma** [comment]
در نسخه ۷.۵.۳ براساس دسته بندی موجود در صفحه داشبورد است
