### ISSUE TITLE
در هنگام ساخت منبع داده جدید  پیشفرض برای نقش اصلی کاربر مجوز داده شود ضمنا در حال حاضر مجوز می دهیم مجوز ذخیره نمی شود

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/dashboard#61]
کاربر تستی که منبع داده می سازد منبع داده خود را نمی تواند ببیند
برای کاربر امکان انتخاب نقش اصلی فراهم شود در این صورت در زمان ایجاد نمودار و منبع داده و صفحه پیشفرض برای نقش اصلیش مجوز داده شود

**Comment by HaShamaei** [comment]
در خصوص نمودار هم همین اتفاق می افتد

**Comment by azetroma** [comment]
در نسخه ۷.۵ اصلاح شده است
