### ISSUE TITLE
انتخاب ردیف ها در هنگام ارتباط منابع داده بر عکس انتخاب می شود

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/dashboard#71]
یک فایل اکسل را با منبع داده تاریخ جوین کردم
و گفتم که از اکسله همه ردیفها بیاید ولی به اشتباه همه ردیف های تاریخ می آمدند

**Comment by azetroma** [comment]
در نسخه ۷.۶.۱ حل شد
