### ISSUE TITLE
لیبل ها ابتدا انگلیسی نمایش داده می شوند سپس فارسی می شوند

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/dashboard#75]
بهتر است پیش فرض فارسی باشند و اگر تنظیمات روی انگلیسی بود به انگلیسی عوض شوند این کمی روی سرعت تاثی گذار است

**Comment by azetroma** [comment]
در نسخه 7.5.3 برطرف شد. 
به دلیل کش کردن برخی از مقادیر در داشبورد ممکن است مشکلی بابت نمایش اطلاعات کش شده پیش بیاید
بنده تست کردم مشکی نبود.
