### ISSUE TITLE
روی یک صفحه رفرش که میزنیم تا صفحه بروز شود به صفحه پیشفرض رانده می شویم

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/dashboard#79]
جدیدا اینجوری شده

**Comment by azetroma** [comment]
لطفا در نسخه جدید دوباره تست شود

**Comment by azetroma** [comment]
هنوز تست کیس درستی در دست نیست. لطفا در صورتی که تکرار پذیری مشکل آماده شد اطلاع دهید
