### ISSUE TITLE
پالایشگاه تبریز : برای دریافت لیست کاربران اکتیو نیاز به کاربر ادمین نباشد و ضمنا فقط ماربران فعال لیست شوند

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/dashboard#91]
با کد زیر فقط نام دامنه پرسیده می شود
    private void getlist3()
        {

            using (var context = new PrincipalContext(ContextType.Domain, "csroll.local"))
            {
                UserPrincipal userPrin = new UserPrincipal(context);
                userPrin.Enabled = true;
                using (var searcher = new PrincipalSearcher(new UserPrincipal(context)))
                {
                    searcher.QueryFilter = userPrin;
                    foreach (var result in searcher.FindAll())
                    {
                        DirectoryEntry de = result.GetUnderlyingObject() as DirectoryEntry;
                       // ADUsersList.Items.Add("First Name: " + de.Properties["givenName"].Value + " Last Name : " + de.Properties["sn"].Value + " SAM account name   : " + de.Properties["samAccountName"].Value + " User principal name: " + de.Properties["userPrincipalName"].Value);
                        Console.WriteLine("First Name: " + de.Properties["givenName"].Value);
                        Console.WriteLine("Last Name : " + de.Properties["sn"].Value);
                        Console.WriteLine("SAM account name   : " + de.Properties["samAccountName"].Value);
                        Console.WriteLine("User principal name: " + de.Properties["userPrincipalName"].Value);
                        Console.WriteLine();
                    }
                }
            }
            Console.ReadLine();
        }

**Comment by azetroma** [comment]
در حال حاضر فقط کاربران فعال آورده می‌شود
بدون نام کاربری و پسورد تست شد ولی کار نمیکند و خطا می‌دهد

**Comment by azetroma** [comment]
#102 این مورد تکراری است
در نسخه ۷.۶.۶ حل شده است
