### ISSUE TITLE
پالایشگاه تبریز : امکان اتولاگین برای کاربران اکتیو فراهم شود

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/dashboard#95]
در حال حاضر پسورد خالیست وامکان اتولاگین نیست
پیشنهاد می شود در هنگام اضافه کردن کاربر اکتیو یک پسورد بزرگ رندوم براش ایجاد بشه
در حال حاضر 500 کاربر اضافه کردند که همه پسورد ها خالیه
یه دستور هم برای پر شدن پسورد خالی برای کاربرای جاری لازمه

**Comment by azetroma** [comment]
در حال حاضر یک پسورد رندوم برای کاربران ست می‌شود.
باید کاربران قبلی پاک شوند و کاربران دوباره اضافه شوند تا پسورد برایشان ست شود.

نسخه ۷.۶.۵
